import './layout.scss'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Fav from '../images/favicon/icons8-lipstick-color-16.png'

const inter = Inter({ subsets: ['latin'] })

interface Metadata {
  title: string;
  description: string;
  favicon?: string;
}

export const metadata: Metadata = {
  title: 'Aksinya.makeup',
  description: 'Generated by create next app',
  // favicon: '../images/favicon/favicon.ico'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
